#! /bin/bash

ICON="/PATH/TO/cmd-kericon/assets/icon.png"
CONFIG_HOME="/PARH/TO/Kerio-VPN/"

if [[ $(ps uax | grep '/usr/sbin/kvpncsvc /var/lib/kerio-control-vpn' | grep -v grep -c) -eq 0 ]]; then
	CONFIG_FILE="$(ls $CONFIG_HOME | fzf --reverse)"
	if [[ ! $(readlink -f /etc/kerio-kvc.conf) == "$CONFIG_HOME$CONFIG_FILE" ]]; then
		sudo ln -sf "$CONFIG_HOME$CONFIG_FILE" /etc/kerio-kvc.conf
	fi
	sudo /etc/init.d/kerio-kvc start && \
		notify-send -i $ICON "Kerio Control VPN Client" "Connected successfully"
else
	sudo /etc/init.d/kerio-kvc stop && \
		notify-send -i $ICON "Kerio Control VPN Client" "Disconnected form server"
fi

